name: Deploy

on:
  push:
    branches: [ live ]
  pull_request:
    branches: [ live ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: live
        path: CovidDailyUpdateBot

    - name: Decrypt .env.gpg file
      working-directory: ./CovidDailyUpdateBot
      run: ./scripts/decrypt_file.sh .env .env.gpg
      env:
        DECRYPT_PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}

    - name: Copy files on remote server
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./CovidDailyUpdateBot
        target: ${{ secrets.DEPLOY_PATH }}
    
    - name: Run updated project on remote server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: ./CovidDailyUpdateBot/scripts/run.sh