name: Test

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug Location
        run: pwd && ls -al

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Setup Poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Cache Poetry Virtual env
        id: cache
        with:
          path: ./venv
          key: poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Run Tests
        run: poetry run python -m unittest -v
    